Additional discription to vehicles categories
igorkis-scrts/A3-Antistasi-Plus pull request #150
Opened 2023-08-12 13:08 UTC by wersal454

## What type of PR is this.
1. [ ] Bug
2. [X] Change
3. [X] Enhancement

### What have you changed and why?
Information:
*Перезалив PR, потому что пришлось удалить репозиторий и начать заново

Добавил дополнительное описание категориям транспорта  

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [X] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:
В планах добавить описание ко всему остальному, но пока что не знаю ка всё работает.
Если одобрят изменения в CV сразу делаю похожий файл и для +, чтобы потом не заморачиваться

2023-08-12 19:21 UTC, igorkis-scrts requested changes
*something here* should be replaced with actual explanation

2023-08-12 19:37 UTC, wersal454 commented
> _something here_ should be replaced with actual explanation

Естественно просто я не знаю что там написать собственно

2023-08-14 06:27 UTC, igorkis-scrts requested changes

2023-08-14 11:50 UTC, igorkis-scrts approved these changes

2023-08-14 11:51 UTC, merged