Added JETS and APEX UAV's
igorkis-scrts/A3-Antistasi-Plus pull request #151
Opened 2023-08-12 14:22 UTC by wersal454

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:

Опять таки схожий запрос который я сделал для CV. Если одобрят, просто меньше работы будет

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2023-08-12 19:20 UTC, igorkis-scrts commented
Можешь расшифровать названия у класснеймов беспилотников (как называются в игре)?

2023-08-12 19:46 UTC, wersal454 commented
> 
B_UAV_05_  - Sentinel
B_T_UAV_03 - MQ-12 Falcon
0_T_UAV_04_CAS_F - KH-3A Fenghuang

2023-08-12 20:13 UTC, igorkis-scrts commented
Я думаю что Fenghuang должен быть в temperate/tropical-темплейтах, ванильный ксатовский - в arid.
У Блуфора же (стандартный и стелс) могут быть во всех вариантах.

2023-08-12 20:25 UTC, wersal454 commented
Ок. Ну я так подумал у ванильного и Fenghuang одинаковый камуфляж поэтому и закинул их во все темплейты.

Если надо раскидаю обратно, но все же думаю оставить ванильный бпла в temperate/tropical (все же одинаковые камуфляжи и почему бы CSAT из тихого океана не использовать и тот дрон и другой)

А у Блюфора всё норм? ничего менять не надо получается ?

2023-08-12 21:36 UTC, wersal454 commented
А ещё у нато появился пустынный камуфляж для вертолётов(кроме транспортного) из Western Sahara(или его в основную игру добавили, я не уверен)
И у бронированного PO-30 Orca есть камуфляж гекс обычный.
Может добавить пустынные камуфляжи для вертов nato в arid и Temparate?
Ну и бронированную Орку в csat arid вместе с камуфляжем

2023-08-13 06:10 UTC, igorkis-scrts commented
В общем, я бы сократил этот PR до только добавления стелс-UAV блуфору.
Пустынные камуфляжи, скорее всего, лежат в Western Sahara и сломают темплейты для тех, у кого это CDLC не куплен или не включен.

2023-08-13 11:04 UTC, wersal454 commented
Вернул CSAT'овские бпла на место.

2023-08-13 11:20 UTC, wersal454 commented
а по поводу камуфляжей можно ведь добавить проверку по типу:

private _transportHelicopters = ["B_Heli_Transport_01_F"];
if (_hasWs) then {
    _transportHelicopters append ["B_ION_Heli_Light_02_unarmed_lxWS"]; (не знаю можно ли убрать "ION" чтобы он заспавнил сразу гексовый вариант ну а если нет то просто добавить в variants гексовый камуфляж
};
["vehiclesHelisTransport", _transportHelicopters] call _fnc_saveToTemplate;

Ну и тоже самое для пустынных вариантов вертов блюфора 
Как я понимаю у них по какой то причине отдельное название к примеру "B_D_Heli_Transport_01_lxWS"

2023-08-14 06:53 UTC, igorkis-scrts requested changes

2023-08-14 07:57 UTC, igorkis-scrts commented
В общем, этот PR должен добавить только Sentinel.

2023-08-14 12:27 UTC, wersal454 commented
https://community.bistudio.com/wiki/Arma_3:_CfgVehicles_WEST нашёл сайт с наименованиями всей техники включая доступные камуфляжные варианты

2023-08-14 12:29 UTC, wersal454 commented
А ещё не знаю повезло ли мне так или версия твоего мода была старая(майская), но у меня ИИ никогда не запрашивал QRFVEHAIRDROP только вручную получилось вызывать. Играл с NATO arid и CSAT arid

2023-08-14 13:21 UTC, wersal454 commented
https://community.bistudio.com/wiki/Western_Sahara_classNames и такой же сайт для ws

2023-08-14 17:32 UTC, igorkis-scrts requested changes
Добавить только Sentinel, остальное не подходит.

2023-08-14 18:27 UTC, wersal454 commented
Всё, добавил только sentinel и mq-12 falcon в аегис

2023-08-14 19:24 UTC, igorkis-scrts requested changes

2023-08-14 19:24 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_NATO_Temperate.sqf
> +["uavsAttack", ["B_T_UAV_03_dynamicLoadout_F", "B_UAV_05_F", "B_W_UAV_02_dynamicLoadout_F"]] call _fnc_saveToTemplate;
Не уверен, что беспилотник вертолётного типа будет работать в текущем коде, там всё написано под самолётные типы, соотвественно стоило бы убрать B_T_UAV_03_dynamicLoadout_F

2023-08-14 19:58 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_NATO_Temperate.sqf
> +["uavsAttack", ["B_T_UAV_03_dynamicLoadout_F", "B_UAV_05_F", "B_W_UAV_02_dynamicLoadout_F"]] call _fnc_saveToTemplate;
Поддержка UAV вроде как отключена на данный момент, разве нет? В fn_initSupports она уж точно не прописана. Плюс ты вроде как активной разработкой не занимаешься уже. Соответственно придётся ждать пока ребята из CV её допилят. Кстати они согласились добавить UAV в моём PR им чтобы потом не заморачиваться.

2023-08-14 20:03 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +["uavsAttack", ["B_UAV_02_dynamicLoadout_F", "UAV_05_Base_F"]] call _fnc_saveToTemplate;
Поменял

2023-08-14 20:36 UTC, igorkis-scrts approved these changes

2023-08-14 20:36 UTC, merged