Added WS mortar APC and some code changes
igorkis-scrts/A3-Antistasi-Plus pull request #170
Opened 2023-08-18 19:34 UTC by wersal454

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:

Добавил в артиллерию бтр с миномётом

Добавил к basic самый базовый HEMMIT
Причины:
1.У него всего два места(по описанию подходит)
2.У него нет возможности перевозить груз(ящики)
3.Почему бы и нет? + Когда я играл я не видел чтобы базовый транспорт вообще спавнился да и функции к basic не подвязаны так что ничего сломает
    
### Issue.
относится к #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes

### How can the changes be tested?
Steps: 
Собственно зачем нужно тестирование. 
1.Потому что как я написал в баг репорте арта не вызывается. Нужно будет проверить после исправления
2.Я накосячил с Magazines видимо код не так работает как я думаю. Поэтому темплейт не загружается
********************************************************
Заметка:
Исправил код лёгких танков:
1. Если наличие хоть какого-то танка в категории необходимо пусть лучше это будет стандартный танк чтобы у не владельцев длс проблем не было.
2. В проверке на длс добавил полную замену сета на танки из длс.

Если изменения норм отпиши чтобы я в этот PR добавил и остальные темплейты.

2023-08-18 21:17 UTC, igorkis-scrts requested changes
Итого, я бы скукожил данный PR до добавления дополнительных типов боеприпасов к артиллерии + сделал это в остальных темплейтах.

2023-08-18 21:17 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +    _artmagazines pushBack ["APC_Wheeled_01_mortar_base_lxWS",["64Rnd_60mm_Mo_LG_lxWS"]];
`_artMagazines` - это хэшмап/словарь пар ключ-значение, не уверен что `pushBack` работает в таком случае. Вроде как, вместо этого используется `set`.

https://community.bistudio.com/wiki/HashMap

2023-08-18 21:17 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +["vehiclesBasic", ["B_Quadbike_01_F", "B_Truck_01_Mover_F"]] call _fnc_saveToTemplate;
Несмотря на то, что vehiclesBasic'и не спавнятся, я бы не стал туда совать грузовик без прицепа. По задумке, этот массив для лёгкой техники вроде квадриков и мотоциклов.

2023-08-18 21:17 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +private _lightTanks = ["B_MBT_01_cannon_F"];
Увы, но в данном случае колесный танк из Tanks DLC - необходимое зло. Большая Меркава, приезжающая на 4-5 вар левеле, повредит балансу.

2023-08-18 21:17 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +private _artillery = if (_hasWs) then {["APC_Wheeled_01_mortar_base_lxWS" ,"B_MBT_01_arty_F", "B_MBT_01_mlrs_F"]} else {["B_MBT_01_arty_F","B_MBT_01_mlrs_F"]};
Оставить как есть, у миномёта может не быть необходимой дальности.

2023-08-18 21:55 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +private _lightTanks = ["B_MBT_01_cannon_F"];
Может тогда совсем пустым оставить? Или же будут проблемы в коде ? Просто давать игрокам возможность захватывать танк ,но без возможности на нём ездить(отсутствие длс) тоже такая себе идея.

2023-08-18 21:55 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +private _artillery = if (_hasWs) then {["APC_Wheeled_01_mortar_base_lxWS" ,"B_MBT_01_arty_F", "B_MBT_01_mlrs_F"]} else {["B_MBT_01_arty_F","B_MBT_01_mlrs_F"]};
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/045eb707-aa09-450c-8d69-3e69b9e7b28c)
4км! Разве не достаточно ? Учитывая что арта бывает довольно близко спавнится. Ну может и не достаточно, но тогда может какие-нибудь проверки добавить? Уж очень жалко что бтр использоваться вообще не будет. Просто  если игроки умудрятся захватить его это будет не оверкилл, потому что урон по площади не достаточно большой и дальность средняя, соответственно в ответку артиллеристам прилетит  быстро.

2023-08-18 21:57 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +    _artmagazines pushBack ["APC_Wheeled_01_mortar_base_lxWS",["64Rnd_60mm_Mo_LG_lxWS"]];
Ничего не понял, но очень интересно

2023-08-18 22:09 UTC, wersal454 commented
По поводу разнообразных боеприпасов, есть много разных напиши тогда конкретно какие добавить
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/b8eaa53a-a3d7-4efe-9f19-b1de5c77bc9a)
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/8360d200-7c60-4743-9bf6-058d6aff8683)

2023-08-18 22:25 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +    _artmagazines pushBack ["APC_Wheeled_01_mortar_base_lxWS",["64Rnd_60mm_Mo_LG_lxWS"]];
Кажется понял.
[player](https://community.bistudio.com/wiki/player) [setVariable](https://community.bistudio.com/wiki/setVariable) ["myMap", [createHashMapFromArray](https://community.bistudio.com/wiki/createHashMapFromArray) [["a",1], ["b",2], ["c",3]]];
[private](https://community.bistudio.com/wiki/private) _myMap [=](https://community.bistudio.com/wiki/a_=_b) [player](https://community.bistudio.com/wiki/player) [getVariable](https://community.bistudio.com/wiki/getVariable) "myMap";
_myMap [set](https://community.bistudio.com/wiki/set) ["z", 4];

2023-08-18 22:27 UTC, wersal454 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +    _artmagazines pushBack ["APC_Wheeled_01_mortar_base_lxWS",["64Rnd_60mm_Mo_LG_lxWS"]];
Хотя нет. Не понял. Видимо надо просто поменять пуш на сет

2023-08-18 23:36 UTC, wersal454 commented
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/e1bcd9f5-c9b4-4a4b-bcb9-6be153341157)
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/1fcc1ea8-1110-485d-9774-352f80578195)
РАБОТАЕТ!
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/8ec0f716-ee4c-464d-af08-77722d17a3f2)

2023-08-19 06:02 UTC, igorkis-scrts commented
Тогда сделать только кассетные и обычные снаряды.

2023-08-19 12:47 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +private _lightTanks = ["B_MBT_01_cannon_F"];
Ну, игре через пару недель будет 10 лет, думаю, у людей без длц было достаточно возможностей ухватить все длц с 50%-75% скидкой чтобы не сильно об этом думать.

2023-08-19 12:48 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +private _artillery = if (_hasWs) then {["APC_Wheeled_01_mortar_base_lxWS" ,"B_MBT_01_arty_F", "B_MBT_01_mlrs_F"]} else {["B_MBT_01_arty_F","B_MBT_01_mlrs_F"]};
На Малдене, например, Артиллерия ОПФОРа может бить вообще с маленького острова в левом верхнем углу карты, и этот островок находится на почтительном расстояния от большой земли. Поэтому артиллерия желательно должна быть довольно дальнобойной.

2023-08-19 13:38 UTC, wersal454 commented
> Тогда сделать только кассетные и обычные снаряды.

Может 155 закинуть ещё и минные снаряды(пп и пт) ? Дымовые ясное дело будут по сути бесполезные так же как и осветительные, а guided и laser guided ИИ скорее всего просто использовать по назначению не сможет(только если игроки захватят и то не знаю как именно эти снаряды работают)

2023-08-19 13:43 UTC, igorkis-scrts commented
> > Тогда сделать только кассетные и обычные снаряды.
> 
> Может 155 закинуть ещё и минные снаряды(пп и пт) ?

В целом, я не против (создаст новые тактические ситуации для игроков с появлением динамических минных полей на их позициях). Я бы добавил только ПП-мины в таком случае, так как артиллерия вызывается в игре против скоплений пехоты.

2023-08-19 14:12 UTC, wersal454 commented
> > > Тогда сделать только кассетные и обычные снаряды.
> > 
> > 
> > Может 155 закинуть ещё и минные снаряды(пп и пт) ?
> 
> В целом, я не против (создаст новые тактические ситуации для игроков с появлением динамических минных полей на их позициях). Я бы добавил только ПП-мины в таком случае, так как артиллерия вызывается в игре против скоплений пехоты.

А как собственно надо их прописать? 
Так
["O_MBT_02_arty_F",["32Rnd_155mm_Mo_shells_O", "6Rnd_155mm_Mo_mine", "2Rnd_155mm_Mo_Cluster"]
или так
["O_MBT_02_arty_F",["32Rnd_155mm_Mo_shells_O"]
["O_MBT_02_arty_F",["6Rnd_155mm_Mo_mine"]
["O_MBT_02_arty_F",["2Rnd_155mm_Mo_Cluster"]

2023-08-19 14:13 UTC, igorkis-scrts commented
Первый вариант.

2023-08-19 14:50 UTC, wersal454 commented
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/005292cc-47af-4272-97cd-b8e6d2fe2030)

2023-08-19 14:51 UTC, igorkis-scrts approved these changes

2023-08-19 14:52 UTC, igorkis-scrts commented
мерж конфликт в Vanilla_AI_AAF

2023-08-19 14:56 UTC, wersal454 commented
> мерж конфликт в Vanilla_AI_AAF

Ну я собственно убрал натовскую 155 и добавил кластерные ракеты

2023-08-19 14:57 UTC, igorkis-scrts commented
Я к тому, что ты должен порешать его в своей ветке, чтобы я мог влить его в 2-3-update.

2023-08-19 15:03 UTC, merged

2023-08-19 15:07 UTC, wersal454 commented
@igorkis-scrts 

Я с merge conflict ещё не сталкивался просто. И нажал на resolve conflict.