Ещё некоторые изменения
igorkis-scrts/A3-Antistasi-Plus pull request #171
Opened 2023-08-19 16:04 UTC by wersal454

## What type of PR is this.
1. [ ] Bug
2. [X] Change
3. [X] Enhancement

### What have you changed and why?
Information:

Забыл внести изменения в остальные NATO темплейты
И несколько изменений в AAF темплейт

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

********************************************************
Notes:
заметил вот такой прикол с пво AAF и прописал шанс такого камуфляжа 0.1, вдруг поможет
![aa](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/afcaa44f-6a2f-4a8b-a7f7-c62f7bda8e95)

2023-08-19 16:12 UTC, wersal454 commented
А ещё для теста(у себя а не в PR) добавил скаут в радар и он нормально заспавнился! Правда если удалить SAM из темплейта то они уже не спавнятся.
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/765aa66f-ab08-4283-8f12-62394cdd398e)

2023-08-19 21:17 UTC, wersal454 commented
После изменений в CSAT temperate темплейт перестал отображаться в игре(даёт загрузить, но пишет в <null> вместо названия и ничего не спавнит)
Да и вообще всё бы перепроверить

2023-08-20 10:14 UTC, igorkis-scrts commented
Ну, проверка и первичное тестирование это прорегатива автора пулл реквеста так как инициатива внесения изменений в код в основной репозиторий входит от него. 🙃

2023-08-20 10:23 UTC, igorkis-scrts requested changes

2023-08-20 10:23 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +    ["I_LT_01_AA_F", ["Olive",0.1]]
прописать `0` если это нежелательный вариант камуфляжа

2023-08-20 10:23 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +private _hasHelicopters = "heli" in A3A_enabledDLC;
убрать строчку насовсем, так как переменная неиспользуется в шаблоне фракции

2023-08-20 10:23 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
> +    ["B_ION_Heli_Light_02_unarmed_lxWS", ["Opfor",1, "Black", 1 , "Black Custom", 1]],
Оставить только 1 камуфляж - Opfor.

2023-08-20 10:23 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
> +private _artillery = if (_hasWs) then {["B_T_APC_Wheeled_01_mortar_lxWS" ,"B_T_MBT_01_arty_F", "B_T_MBT_01_mlrs_F"]} else {["B_T_MBT_01_arty_F","B_T_MBT_01_mlrs_F"]};
Про миномёт мы уже говорили - он не подходит.

2023-08-20 10:23 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
> +private _artillery = if (_hasWs) then {["B_T_APC_Wheeled_01_mortar_lxWS" ,"B_T_MBT_01_arty_F", "B_T_MBT_01_mlrs_F"]} else {["B_T_MBT_01_arty_F","B_T_MBT_01_mlrs_F"]};
Про миномёт мы уже говорили - он не подходит.

2023-08-20 10:23 UTC, igorkis-scrts commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +    ["APC_Wheeled_01_mortar_base_lxWS", ["showCamonetHull",0.3,"showCamonetTurret",0.3,"showSLATHull",0.3,"showSLATTurret",0.3]],
Замена существующего класснейма уберет вероятности дополнительного обвеса для этого БТР, плюс этот миномёт на колесах, вроде как, не должен использоваться.

2023-08-20 10:23 UTC, igorkis-scrts commented
По итогам ревью - все изменения не подходят текущей кодовой базе по различным соображениям.

2023-08-20 10:23 UTC, closed without merging

2023-08-20 15:19 UTC, wersal454 commented
@igorkis-scrts 
1.Что-то слишком быстро ты закрыл PR. Даже изменения не дал внести. :[
   Ты мне расскажи про теплейт AAF  по подробнее. Я понял что нужно убрать строчки некоторые в начале и изменить 
   на 0 вероятность спавна камуфляжа.
   А остальные то норм? Ты заметил что вертолёт нато из атакующих убрал?

2.Натовские темплейты: понял про миномёт(может позже придумаю как его добавить).
   Ты опять таки заметил что я перенёс apc гусеничный в IFV? В прошлый раз объяснял причину(высокая выживаемость 
   и наличие гранатомёта).

3.Про CSATовские тоже чет не понял. Ты уверен что не нужны чёрные камуфляжи(у тебя до этого они были просто)
   Так же напиши я собственно правильно прописал код нескольких камуфляжей? Синтаксис там и вероятности.
   И как ты смотришь правильные названия камуфляжей? В 3den ? Или в виртуальном арсенале ?

2023-08-20 16:16 UTC, igorkis-scrts commented
Убранный вертолёт у AAF  - хорошо. Зануленный оливковый камуфляж - тоже. Черный камуфляж у вертолётов допустим, но с вероятностью 0.2 каждый кроме гекса (можно, раскидать, соответственно, вероятности 0.6-0.2-0.2 в тех массивах).

Хорошим решением будет создать новый PR только с этими изменениями.

2023-08-20 16:17 UTC, igorkis-scrts commented
По остальному - на мой вкус, это не подходит плюсу.

2023-08-20 16:23 UTC, wersal454 commented
@igorkis-scrts 
Ок уже в процессе считай

И ты так и не ответил про натовский темп. "Ты опять таки заметил что я перенёс apc гусеничный в IFV? В прошлый раз объяснял причину(высокая выживаемость и наличие гранатомёта)."
В прошлом PR ты это одобрил если что.

И вот это вот очень уж надо мне на будущее знать!
"Так же напиши я собственно правильно прописал код нескольких камуфляжей? Синтаксис там и вероятности.
И как ты смотришь правильные названия камуфляжей? В 3den ? Или в виртуальном арсенале ?"

2023-08-20 16:30 UTC, igorkis-scrts commented
> "Ты опять таки заметил что я перенёс apc гусеничный в IFV? В прошлый раз объяснял причину(высокая выживаемость и наличие гранатомёта)."

Да, это нормально.

> Так же напиши я собственно правильно прописал код нескольких камуфляжей?

Синтаксис правильный, вероятности неправильны - значения должны быть от нуля до единицы.
```
Черный камуфляж у вертолётов допустим, но с вероятностью 0.2 каждый кроме гекса (можно, раскидать, соответственно, вероятности 0.6-0.2-0.2 в тех массивах).
```

> И как ты смотришь правильные названия камуфляжей? В 3den ? Или в виртуальном арсенале ?"

В виртуальном арсенале при экспорте в буфер обмена показывается правильный камуфляж.