Civ plane encounter + civ plane category for vanilla civ
igorkis-scrts/A3-Antistasi-Plus pull request #188
Opened 2023-08-26 22:50 UTC by wersal454

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:

Добавил случ. встречу с гражданским самолётом.    

### Please specify which Issue this PR Resolves.
closes #187

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/476d1cbd-4a34-4eee-afeb-38d395293b66)

2023-08-26 23:10 UTC, igorkis-scrts requested changes
1. Самолёты не проброшены в остальные игровые системы  и живут в вакууме (только этой функции). Можно посмотреть как работают vehiclesCivHeli в остальном коде.
2. Нет поддержки других модов (Аегис, SOGPF, RHS, RHS+3CBF).
3. Нет проброса функции в гейм-ивент-петлю, автоматический выборщик ивентов не сможет выбрать эту функцию.
4. Нет проброса в `CfgFunctions`, функция не зарегстрирована и не может быть вызвана через `call` или `spawn`.

2023-08-26 23:20 UTC, wersal454 commented
> 1. Самолёты не проброшены в остальные игровые системы  и живут в вакууме (только этой функции). Можно посмотреть как работают vehiclesCivHeli в остальном коде.
> 2. Нет поддержки других модов (Аегис, SOGPF, RHS, RHS+3CBF).
> 3. Нет проброса функции в гейм-ивент-петлю, автоматический выборщик ивентов не сможет выбрать эту функцию.
> 4. Нет проброса в `CfgFunctions`, функция не зарегстрирована и не может быть вызвана через `call` или `spawn`.

Я представлю что понял всё что ты написал.
1.Ага
2.Если не у всех модсетов есть самолёты из модов , можно ли запихнуть из ванилы самолёт ?
3.Ага
4.Сделано

2023-08-27 00:35 UTC, wersal454 commented
Вроде всё, только первый пункт уточни

И я тебе больше PRы не кидаю с фичами ? Если да то объясни как добавить лтшки в магазин а то я их закинул, но они не отображаются. И почему собственно в магазине не применяется камуфляж к apcшке к примеру?

2023-08-27 07:09 UTC, igorkis-scrts approved these changes

2023-08-27 07:09 UTC, igorkis-scrts commented
lgtm

2023-08-27 07:09 UTC, merged

2023-08-27 08:04 UTC, igorkis-scrts commented
> И я тебе больше PRы не кидаю с фичами ? 

Пулл-реквесты с фичами - думаю, да, можно не кидать. Этот пулл реквест я выпущу хотфиксом, но про остальные, если таковые будут, сложно сказать.

> Если да то объясни как добавить лтшки в магазин а то я их закинул, но они не отображаются. И почему собственно в магазине не применяется камуфляж к apcшке к примеру?

Да вроде всё работает. Тоже закину в хотфикс.
![20230827105048_1](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/6746043/79baed3a-1132-4346-8784-eb9571103c60)

Магазин не поддерживает камуфляжи из-за особенностей работы спавна ребельской техники и гаража. Также в гаражный код нельзя добавить проброс камо при превью и установке техники ввиду его APL-ND лицензии - я не могу почти ничего менять в коде гаража.

2023-08-27 10:43 UTC, wersal454 commented
> Пулл-реквесты с фичами - думаю, да, можно не кидать. Этот пулл реквест я выпущу хотфиксом, но про остальные, если таковые будут, сложно сказать.

![e3a_yapfiles ru](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/7eea70e9-5434-4b45-99a8-f8ab81bc37ab)